apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: efs-csi-driver
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: aws-efs-csi-driver
      version: 3.1.8
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
        namespace: flux-system
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: replace
                path: /metadata/labels
                value:
                  gwcp.guidewire.com/app-name: kubevela-core
                  gwcp.guidewire.com/version: "1.10.3"
                  gwcp.guidewire.com/created-by: pod-ajanta
                  gwcp.guidewire.com/maintained-by: pod-ajanta
                  gwcp.guidewire.com/tenant-name: tenant-shared
                  gwcp.guidewire.com/dept: "275"
                  change-by: ajanta
            target:
              kind: ".*"
  values:
    controller:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/efs-csi-driver
    node:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/efs-csi-driver
    storageClasses:
      - name: efs-csi-infra-sc
        mountOptions:
          - tls
          - iam
